In [1]:
import random


class Environment:
    def __init__(self):
        self.steps_left = 10

    def get_observation(self) -> list[float]:
        return [0.0, 0.0, 0.0]

    def get_actions(self) -> list[int]:
        return [0, 1]

    def is_done(self) -> bool:
        return self.steps_left == 0

    def action(self, action: int) -> float:
        if self.is_done():
            raise RuntimeError("Environment is done")
        self.steps_left -= 1
        return random.random()


class Agent:
    def __init__(self):
        self.total_reward = 0

    def step(self, env: Environment):
        current_observation = env.get_observation()
        actions = env.get_actions()
        reward = env.action(random.choice(actions))
        self.total_reward += reward

In [2]:
env = Environment()
agent = Agent()
while not env.is_done():
    agent.step(env)

In [4]:
import gym

env = gym.make('CartPole-v1')

In [6]:
obs = env.reset()
obs

(array([0.02111898, 0.00135134, 0.02777854, 0.00716735], dtype=float32), {})

In [7]:
env.action_space

Discrete(2)

In [12]:
env.step(0)

(array([ 0.01727396, -0.1950384 ,  0.03458628,  0.32797697], dtype=float32),
 1.0,
 False,
 False,
 {})

In [13]:
env.action_space.sample()

1

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
a = torch.FloatTensor(3,2)

In [4]:
print(a)

tensor([[1.1888e+29, 1.2373e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [5]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
n = np.zeros(shape=(3,2), dtype=np.float16)

In [7]:
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float16)

In [8]:
b=torch.tensor(n)

In [9]:
print(b)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float16)


In [11]:
b = b.to('cuda')

In [12]:
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], device='cuda:0', dtype=torch.float16)

In [13]:
print(b)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], device='cuda:0', dtype=torch.float16)
